### ISSUE TITLE
如何复现实验结果以及替换自己的数据集呢？

### ISSUE THREAD

**Issue by Spark-lens** [thatgeeman/ts_vae-lstm#1]

**Comment by thatgeeman** [comment]
Thanks for raising this issue, Currently the notebooks in nbs/ directory should be sufficient. Meanwhile I can prepare a few scripts to automate the training and detection steps.

**Comment by thatgeeman** [comment]
@Spark-lens I have the scripts for reproducibility in the main (e0e0131) branch now. Please raise a new issue if something doesnt work! Thank you!
